spring:
  application:
    name: gateway-server   
  cloud: 
   gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"   
      routes:      
      - id: servFormacion
        uri: lb://servicio-formacion#http://localhost:7000
        predicates:
          - Path=/sformacion/**
        filters:
          - RewritePath=/sformacion/*, /      
server:
  port: 9000
eureka:
  client:
    register-with-eureka: false
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka



